name: zeko_hotel_crm
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5

  # Local Storage
  shared_preferences: ^2.3.2

  # Networking
  http: ^1.2.2

  # Language Support
  flutter_localizations:
    sdk: flutter
  intl: any

  # UI
  skeletonizer: ^1.4.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/platform/
    - assets/country-code-with-flag.json